export interface IHotProductViewData {
  id: string;
  imgSrc: ResourceStr;
  title: ResourceStr;
  content: ResourceStr;
}


export const hotProductViewDataSet: IHotProductViewData[] = [
  {
    id: "1",
    imgSrc: $r('app.media.enablement_pic1'),
    title: $r('app.string.enablement_title'),
    content: $r('app.string.enablement_content'),
  },
  {
    id: "2",
    imgSrc: $r('app.media.enablement_pic2'),
    title: $r('app.string.enablement_title'),
    content: $r('app.string.enablement_content'),
  },
  {
    id: "3",
    imgSrc: $r('app.media.enablement_pic3'),
    title: $r('app.string.enablement_title'),
    content: $r('app.string.enablement_content'),
  },
  {
    id: "4",
    imgSrc: $r('app.media.enablement_pic4'),
    title: $r('app.string.enablement_title'),
    content: $r('app.string.enablement_content'),
  },
  {
    id: "5",
    imgSrc: $r('app.media.enablement_pic5'),
    title: $r('app.string.enablement_title'),
    content: $r('app.string.enablement_content'),
  },
  {
    id: "6",
    imgSrc: $r('app.media.enablement_pic6'),
    title: $r('app.string.enablement_title'),
    content: $r('app.string.enablement_content'),
  },
  {
    id: "7",
    imgSrc: $r('app.media.enablement_pic7'),
    title: $r('app.string.enablement_title'),
    content: $r('app.string.enablement_content'),
  },
  {
    id: "8",
    imgSrc: $r('app.media.enablement_pic8'),
    title: $r('app.string.enablement_title'),
    content: $r('app.string.enablement_content'),
  }]